### ISSUE TITLE
Specs to Issues

### ISSUE THREAD

**Issue by JoseCortesSarmiento** [JoseCortesSarmiento/profile-admin#4]
Add specs to issues (Descriptions, Mockups, Class Diagrams, etc) regarding to frontend milestone

**Comment by ImpersPv** [comment]
La documentación de los issues fue terminada:
1. Descripción - Hecho
2. Mockups - Hecho
3. Class Diagram - Hecho - Nota: Ninguno aplicó
4. Unit tests - Hecho
